<%@ Page Language="C#" AutoEventWireup="true" CodeFile="servicesview.aspx.cs" Inherits="servicesview" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            font-size: xx-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <strong><span class="style1">SERVICES TAKEN BY USER</span></strong><br />
        <asp:HyperLink ID="HyperLink1" runat="server" 
            NavigateUrl="~/paymentdetailss.aspx">payment details</asp:HyperLink>
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="venue" HeaderText="venue" SortExpression="venue" />
                <asp:BoundField DataField="cetering" HeaderText="cetering" 
                    SortExpression="cetering" />
                <asp:BoundField DataField="transport" HeaderText="transport" 
                    SortExpression="transport" />
                <asp:BoundField DataField="partyhall" HeaderText="partyhall" 
                    SortExpression="partyhall" />
                <asp:BoundField DataField="dj" HeaderText="dj" SortExpression="dj" />
                <asp:BoundField DataField="lighting" HeaderText="lighting" 
                    SortExpression="lighting" />
                <asp:BoundField DataField="entertainment" HeaderText="entertainment" 
                    SortExpression="entertainment" />
                <asp:BoundField DataField="photographer" HeaderText="photographer" 
                    SortExpression="photographer" />
                <asp:BoundField DataField="weddingdate" HeaderText="weddingdate" 
                    SortExpression="weddingdate" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            
            SelectCommand="SELECT [venue], [cetering], [transport], [partyhall], [dj], [lighting], [entertainment], [photographer], [weddingdate] FROM [tb2]" UpdateCommand="UPDATE [tb2] set [venue]=@venue, [cetring]=@catering, [transport]=@transport, [partyhall]=@partyhall, [dj]=@dj, [lighting]=@lighting, [entertainment]=@entertainment, [photographer]=@photographer, [weddingdate]=@weddingdate" DeleteCommand="DELETE from [tb2]">
        </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
